_target_: main.Custom_Network

criterion: CrossEntropyLoss

layers:
  - type: "Flatten"
    arguments: null
    activation: null

  - type: "Linear"
    arguments:
      in_features: 3072
      out_features: 256
    activation: "ReLU"

  - type: "Linear"
    arguments:
      in_features: 256
      out_features: 256
    activation: "ReLU"

  - type: "Linear"
    arguments:
      in_features: 256
      out_features: 10
    activation: null

  - type: "Softmax"
    arguments:
      dim: 1
    activation: null

# could be one of 'kaiming_uniform_', 'kaiming_normal_', 'xavier_uniform_'
init_method: kaiming_normal_